name: Docker Image Downloader

on:
  workflow_dispatch: # 允许你手动点击按钮触发任务

jobs:
  download-and-pack:
    runs-on: ubuntu-latest
    steps:
      - name: Pull Docker Image
        run: |
          # 拉取目标镜像
          docker pull ghcr.io/openfreeenergy/openfe:1.11.1-apptainer
          
      - name: Save Image to Tar
        run: |
          # 将镜像导出为 tar 包
          docker save ghcr.io/openfreeenergy/openfe:1.11.1-apptainer -o openfe.tar
          
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: openfe-package  # 下载时的压缩包文件名
          path: openfe.tar      # 要上传的文件
          retention-days: 1     # 自动保存天数，下载完就会过期，节省空间
