name: Docker Image Downloader

# 触发条件：允许在 Actions 页面手动点击运行
on:
  workflow_dispatch:

jobs:
  download-job:
    runs-on: ubuntu-latest
    # 设置较长的超时时间，防止镜像过大导致中断
    timeout-minutes: 60 

    steps:
      - name: Check disk space
        run: df -h # 运行前检查磁盘空间，确保有足够位置存放镜像

      - name: Pull Docker Image
        run: |
          docker pull ghcr.io/openfreeenergy/openfe:1.11.1-apptainer

      - name: Save Image to Tar
        run: |
          # 建议使用 gzip 压缩，这样下载的文件会更小
          docker save ghcr.io/openfreeenergy/openfe:1.11.1-apptainer | gzip > openfe_1.11.1.tar.gz

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: openfe-image-package
          path: openfe_1.11.1.tar.gz
          # 设置保留 1 天，下载完自动清理，保护隐私
          retention-days: 1
          # 禁用压缩以提高上传速度（因为我们上面已经手动 gzip 压缩过了）
          compression-level: 0
